/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gazelle_boutiqe;

import images.image_class;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


 
public class home extends javax.swing.JFrame {
/**
    public class dark  extends JFrame{
        public void dark(){
                Color black=null;
        if(darkmode.isSelected()){
            black =new Color(0,0,0);
            //////////////////////////////////
            homePanel.setBackground(black);
            menu.setForeground(Color.WHITE);
            company.setForeground(Color.WHITE);
            sells.setForeground(Color.WHITE);
            extras.setForeground(Color.WHITE);
            customer.setForeground(Color.WHITE);
            porduct.setForeground(Color.WHITE);
            staff.setForeground(Color.WHITE);
            attend.setForeground(Color.WHITE);
            reports.setForeground(Color.WHITE);
            
            
            
        }else{
            homePanel.setBackground(Color.white);
            
            menu.setForeground(Color.black);
            company.setForeground(Color.black);
            sells.setForeground(Color.black);
            extras.setForeground(Color.black);
            customer.setForeground(Color.black);
            porduct.setForeground(Color.black);
            staff.setForeground(Color.black);
            attend.setForeground(Color.black);
            reports.setForeground(Color.black);
             
             
        }
        }
    }
    * */
    /**
     * Creates new form home
     */

    public home() {
         initComponents();
         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         dark_mode.applyTheme(this);
         setLocationRelativeTo(null);
         setResizable(false);
        //image_class.setImage( this, "image/Code Crafters.jpg",1040, 567);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel = new javax.swing.JPanel();
        company = new javax.swing.JButton();
        menu = new javax.swing.JLabel();
        porduct = new javax.swing.JButton();
        customer = new javax.swing.JButton();
        staff = new javax.swing.JButton();
        reports = new javax.swing.JButton();
        sells = new javax.swing.JButton();
        extras = new javax.swing.JButton();
        attend = new javax.swing.JButton();
        darkmode = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        homePanel.setBackground(new java.awt.Color(255, 255, 255));

        company.setBackground(java.awt.Color.blue);
        company.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        company.setText("مشخصات شرکت");
        company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyActionPerformed(evt);
            }
        });

        menu.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        menu.setForeground(new java.awt.Color(51, 0, 255));
        menu.setText("مینوی اصلی");

        porduct.setBackground(java.awt.Color.blue);
        porduct.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        porduct.setText("محصولات");
        porduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porductActionPerformed(evt);
            }
        });

        customer.setBackground(java.awt.Color.blue);
        customer.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        customer.setText("مشتری");
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });

        staff.setBackground(java.awt.Color.blue);
        staff.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        staff.setText("کارمندان");
        staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffActionPerformed(evt);
            }
        });

        reports.setBackground(java.awt.Color.blue);
        reports.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        reports.setText("گزارشات");
        reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsActionPerformed(evt);
            }
        });

        sells.setBackground(java.awt.Color.blue);
        sells.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        sells.setText("فروشات");
        sells.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellsActionPerformed(evt);
            }
        });

        extras.setBackground(java.awt.Color.blue);
        extras.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        extras.setText("مصارف");
        extras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extrasActionPerformed(evt);
            }
        });

        attend.setBackground(java.awt.Color.blue);
        attend.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        attend.setText("گدام");
        attend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendActionPerformed(evt);
            }
        });

        darkmode.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        darkmode.setText("حالت شب");
        darkmode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        darkmode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkmodeActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel11.setText("developed by Code-Crafters-Company    2024");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(darkmode)
                        .addGap(471, 471, 471)
                        .addComponent(menu))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)))
                .addContainerGap(528, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(attend, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(staff, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(extras, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(sells, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(porduct, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(reports, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(company, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(147, 147, 147))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(darkmode)
                    .addComponent(menu))
                .addGap(70, 70, 70)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reports, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(company, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sells, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porduct, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extras, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attend, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staff, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyActionPerformed
        // TODO add your handling code here:
        com_det obj=new com_det();
        obj.setVisible(true);
         dispose();
        
    }//GEN-LAST:event_companyActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        // TODO add your handling code here:
        customers obj=new customers();
        obj.setVisible(true);
         dispose();
    }//GEN-LAST:event_customerActionPerformed

    private void porductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porductActionPerformed
        // TODO add your handling code here:
        photo obj=new photo();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_porductActionPerformed

    private void staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffActionPerformed
        // TODO add your handling code here:
        staff obj=new staff();
        obj.setVisible(true);
         dispose();
    }//GEN-LAST:event_staffActionPerformed

    private void reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsActionPerformed
        // TODO add your handling code here:
        reports obj=new reports();
        obj.setVisible(true);
         dispose();
    }//GEN-LAST:event_reportsActionPerformed

    private void sellsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellsActionPerformed
        // TODO add your handling code here:
        sells obj=new sells();
        obj.setVisible(true);
         dispose();
    }//GEN-LAST:event_sellsActionPerformed

    private void extrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extrasActionPerformed
        // TODO add your handling code here:\
        extras obj=new extras();
        obj.setVisible(true);
         dispose();
    }//GEN-LAST:event_extrasActionPerformed

    private void attendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "بزودی!!!!!");
    }//GEN-LAST:event_attendActionPerformed

    private void darkmodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkmodeActionPerformed
        // TODO add your handling code here:
        dark_mode.switchDarkmode();
        for(JFrame frame : getAllOpenFrames()){
            dark_mode.applyTheme(frame);
            frame.repaint();
        }

    }//GEN-LAST:event_darkmodeActionPerformed
    private java.util.List<JFrame> getAllOpenFrames(){
        java.util.List<JFrame> frames=new java.util.ArrayList<>();
        for(java.awt.Window window : java.awt.Window.getWindows()){
            if(window instanceof JFrame){
                frames.add((JFrame) window);
            }
        }
        return frames;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attend;
    private javax.swing.JButton company;
    private javax.swing.JButton customer;
    private javax.swing.JCheckBox darkmode;
    private javax.swing.JButton extras;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel menu;
    private javax.swing.JButton porduct;
    private javax.swing.JButton reports;
    private javax.swing.JButton sells;
    private javax.swing.JButton staff;
    // End of variables declaration//GEN-END:variables
}
